/*
 * This file is part of Gradoop.
 *
 * Gradoop is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Gradoop is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Gradoop. If not, see <http://www.gnu.org/licenses/>.
 */

package org.gradoop.flink.model.impl.operators.nest;

import org.apache.flink.api.java.DataSet;
import org.gradoop.common.model.impl.id.GradoopId;
import org.gradoop.common.model.impl.pojo.Edge;
import org.gradoop.common.model.impl.pojo.GraphHead;
import org.gradoop.common.model.impl.pojo.GraphHeadFactory;
import org.gradoop.common.model.impl.pojo.Vertex;
import org.gradoop.flink.model.impl.GraphCollection;
import org.gradoop.flink.model.impl.LogicalGraph;
import org.gradoop.flink.model.impl.functions.epgm.Id;
import org.gradoop.flink.model.impl.operators.nest.functions.GraphHeadToVertex;
import org.gradoop.flink.model.impl.operators.nest.model.indices.NestedResult;
import org.gradoop.flink.model.impl.operators.nest.model.indices.NestingIndex;
import org.gradoop.flink.model.impl.operators.nest.operators.NestingLogic;
import org.gradoop.flink.model.impl.operators.nest.tuples.Hexaplet;

/**
 * Implements the nesting operator for the EPGM data model. Given a graph describing the groundtruth
 * information and a collection of graph representing the mined patterns, it returns a nested graph
 * where each vertex is either a vertex representing a graph in the graph collection that contains
 * at least one match with the ground truth or a non-matcher vertex. The edges from the former
 * graph are also inherited.
 */
public class Nesting extends NestingBase {

  /**
   * The actual id to be associated to the returned graph
   */
  private final GradoopId graphId;

  /**
   * Using the FlatModel if we have a chain of different operations to be optimized
   */
  private LogicalGraph flattenedGraph;

  /**
   * Left index mapping
   */
  private NestingIndex graphIndex;

  /**
   * Right index mapping
   */
  private NestingIndex collectionIndex;

  /**
   * Intermediate indexing result
   */
  private NestedResult intermediateResult;

  /**
   * Setting the outcome of the previous computation
   */
  private DataSet<Hexaplet> previousComputation;

  /**
   * A default id is generated by using the GraphHeadFactory
   * @param ghf Generating the ids for the headers
   */
  public Nesting(GraphHeadFactory ghf) {
    this(ghf.createGraphHead().getId());
  }

  /**
   * A default id is associated to the graph
   * @param graphId Id to be associated to the new graph
   */
  public Nesting(GradoopId graphId) {
    this.graphId = graphId;
    this.flattenedGraph = null;
    this.previousComputation = null;
  }

  /**
   * Default internal initialization for the operator
   * @param graph        Graph to be nested
   * @param collection  Nesting information
   */
  protected void initialize(LogicalGraph graph, GraphCollection collection) {
    // Generating the model only if it is required
    flatten(graph, collection);

    // Suppose that both operands must share the same execution environment
    NestingLogic nesting = new NestingLogic();

    // Extracting the indexing structures for both graphs
    graphIndex = createIndex(graph);
    collectionIndex = createIndex(collection);

    // At this step the FlatModel is never used, since I only change the index representation
    intermediateResult = nesting.execute(graphIndex, collectionIndex);
    previousComputation = intermediateResult.getPreviousComputation();
  }

  private void flatten(LogicalGraph graph, GraphCollection collection) {
  /*
 * Creating the flat model containing the information of everything that happens, from the
 * left operand to the graph collection
 */
    if (flattenedGraph == null) {
      DataSet<GraphHead> heads = graph.getGraphHead().union(collection.getGraphHeads()).distinct(new Id<>());

      DataSet<Vertex> nestedVertices = heads.map(new GraphHeadToVertex());

      DataSet<Vertex> vertices =
        graph.getVertices().union(collection.getVertices()).distinct(new Id<>()).union(nestedVertices);

      DataSet<Edge> edges = graph.getEdges().union(collection.getEdges()).distinct(new Id<>());

      // Getting the model for defining the associated model
      flattenedGraph = flattenedGraph.fromDataSets(heads, vertices, edges, graph.getConfig());
    }
  }

  /**
   * Returns…
   *
   * @return the intermediate indexing result, that could be used a next time for
   * updating the edges
   */
  public NestedResult getIntermediateResult() {
    return intermediateResult;
  }

  /**
   * Returns…
   * @return  the indexing for the nesting interface
   */
  public NestingIndex getCollectionIndex() {
    return collectionIndex;
  }

  /**
   * Returns…
   * @return  the id to be associated to the resulting graph
   */
  public GradoopId getGraphId() {
    return graphId;
  }

  /**
   * Returns…
   * @return the normalized graph containing the information for the whole graphs
   * within the graph
   */
  public LogicalGraph getNormalizedRepresentation() {
    return flattenedGraph;
  }

  @Override
  public LogicalGraph execute(LogicalGraph graph, GraphCollection collection) {
    initialize(graph, collection);

    // Converting the result to the standard EPGM model
    return toLogicalGraph(intermediateResult, flattenedGraph);
  }

  @Override
  public DataSet<Hexaplet> getPreviousComputation() {
    return previousComputation;
  }

  @Override
  public String getName() {
    return getClass().getName();
  }

}
