# https://docs.travis-ci.com/user/reference/overview/
sudo: required
dist: trusty

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - os: windows

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/org/gradoop/

language: java

osx_image: xcode9.3