/*
 * Copyright © 2014 - 2018 Leipzig University (Database Research Group)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradoop.flink.model.impl.operators.sampling;

/**
 * Collected constants for sampling operator
 */
final class SamplingConstants {

  /**
   * Key of a property generated by {@link RandomNonUniformVertexSampling}
   */
  static final String PROPERTY_KEY_MAX_DEGREE = "_maxDegree";

  /**
   * Key of a property generated by {@link RandomVertexNeighborhoodSampling}
   */
  static final String PROPERTY_KEY_SAMPLED = "sampled";


  /**
   The caller references the constants using <tt>SamplingConstants.PROPERTY_KEY_MAX_DEGREE</tt>,
   and so on. Thus, the caller should be prevented from constructing objects of
   this class, by declaring this private constructor.
   */
  private SamplingConstants() {
    // this prevents even the native class from calling this constructor
    throw new AssertionError();
  }
}
