/**
 * Benchmarking programs tailored to run on Graphalytics social network
 * datasets.
 *
 * Graphs used with these benchmarks are generated by the LDBC SNB data
 * generator, which is available at https://github.com/ldbc/ldbc_snb_datagen.
 */
package org.gradoop.examples.sna;
