/*
 * This file is part of Gradoop.
 *
 * Gradoop is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Gradoop is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Gradoop. If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.04 at 10:32:38 AM CET
//


package org.gradoop.flink.io.impl.xmlbasedcsv.pojos;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.gradoop.org/flink/io/impl/csv/pojos}columns"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.gradoop.org/flink/io/impl/csv/pojos}graphhead"/&gt;
 *           &lt;element ref="{http://www.gradoop.org/flink/io/impl/csv/pojos}vertex"/&gt;
 *           &lt;element ref="{http://www.gradoop.org/flink/io/impl/csv/pojos}edge"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.gradoop.org/flink/io/impl/csv/pojos}csvattributes"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
  "columns",
  "graphhead",
  "vertex",
  "edge"
})
@XmlRootElement(name = "csv")
public class Csv
  implements Serializable
{

  private final static long serialVersionUID = 1L;
  @XmlElement(required = true)
  protected Columns columns;
  protected Graphhead graphhead;
  protected Vertex vertex;
  protected Edge edge;
  @XmlAttribute(name = "name")
  protected String name;
  @XmlAttribute(name = "charset")
  protected String charset;
  @XmlAttribute(name = "separator")
  protected String separator;

  /**
   * Gets the value of the columns property.
   *
   * @return
   *     possible object is
   *     {@link Columns }
   *
   */
  public Columns getColumns() {
    return columns;
  }

  /**
   * Sets the value of the columns property.
   *
   * @param value
   *     allowed object is
   *     {@link Columns }
   *
   */
  public void setColumns(Columns value) {
    this.columns = value;
  }

  /**
   * Gets the value of the graphhead property.
   *
   * @return
   *     possible object is
   *     {@link Graphhead }
   *
   */
  public Graphhead getGraphhead() {
    return graphhead;
  }

  /**
   * Sets the value of the graphhead property.
   *
   * @param value
   *     allowed object is
   *     {@link Graphhead }
   *
   */
  public void setGraphhead(Graphhead value) {
    this.graphhead = value;
  }

  /**
   * Gets the value of the vertex property.
   *
   * @return
   *     possible object is
   *     {@link Vertex }
   *
   */
  public Vertex getVertex() {
    return vertex;
  }

  /**
   * Sets the value of the vertex property.
   *
   * @param value
   *     allowed object is
   *     {@link Vertex }
   *
   */
  public void setVertex(Vertex value) {
    this.vertex = value;
  }

  /**
   * Gets the value of the edge property.
   *
   * @return
   *     possible object is
   *     {@link Edge }
   *
   */
  public Edge getEdge() {
    return edge;
  }

  /**
   * Sets the value of the edge property.
   *
   * @param value
   *     allowed object is
   *     {@link Edge }
   *
   */
  public void setEdge(Edge value) {
    this.edge = value;
  }

  /**
   * Gets the value of the name property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the charset property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getCharset() {
    return charset;
  }

  /**
   * Sets the value of the charset property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setCharset(String value) {
    this.charset = value;
  }

  /**
   * Gets the value of the separator property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getSeparator() {
    return separator;
  }

  /**
   * Sets the value of the separator property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setSeparator(String value) {
    this.separator = value;
  }

}
