//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.04 at 10:32:38 AM CET 
//


package org.gradoop.flink.io.impl.xmlbasedcsv.pojos;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java-Klasse für staticorreference complex type.
 *
 * <p>Das folgende Schemafragment gibt den erwarteten Content an, der in dieser Klasse enthalten ist.
 *
 * <pre>
 * &lt;complexType name="staticorreference"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{http://www.gradoop.org/flink/io/impl/csv/pojo}static"/&gt;
 *           &lt;element ref="{http://www.gradoop.org/flink/io/impl/csv/pojo}ref" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{http://www.gradoop.org/flink/io/impl/csv/pojo}ref"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{http://www.gradoop.org/flink/io/impl/csv/pojo}reference"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "staticorreference", propOrder = {
  "content"
})
@XmlSeeAlso({
  Source.class,
  Target.class,
  Graph.class
})
public class Staticorreference implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElementRefs({
      @XmlElementRef(name = "static", namespace = "http://www.gradoop.org/flink/io/impl/xmlbasedcsv/pojo", type = Static.class, required = false),
      @XmlElementRef(name = "ref", namespace = "http://www.gradoop.org/flink/io/impl/xmlbasedcsv/pojo", type = Ref.class, required = false),
      @XmlElementRef(name = "reference", namespace = "http://www.gradoop.org/flink/io/impl/xmlbasedcsv/pojo", type = Reference.class, required = false)
    })
    protected List<Serializable> content;

    /**
     * Ruft das restliche Contentmodell ab.
     *
     * <p>
     * Sie rufen diese "catch-all"-Eigenschaft aus folgendem Grund ab:
     * Der Feldname "Ref" wird von zwei verschiedenen Teilen eines Schemas verwendet. Siehe:
     * Zeile 103 von file:/C:/Users/Stephan/Dropbox/Programming/IntelliJ/Pojo-Creator/src/main/resources/schemas/csv_format.xsd
     * Zeile 100 von file:/C:/Users/Stephan/Dropbox/Programming/IntelliJ/Pojo-Creator/src/main/resources/schemas/csv_format.xsd
     * <p>
     * Um diese Eigenschaft zu entfernen, wenden Sie eine Eigenschaftenanpassung für eine
     * der beiden folgenden Deklarationen an, um deren Namen zu ändern:
     * Gets the value of the content property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Static }
     * {@link Reference }
     * {@link Ref }
     *
     *
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}