package org.gradoop.flink.model.impl.operators.nest2;

import org.gradoop.common.model.impl.id.GradoopId;
import org.gradoop.common.model.impl.pojo.GraphHeadFactory;

/**
 * Created by vasistas on 30/03/17.
 */
public class NestWithDisjunctive extends Nest {

  /**
   * A default id is generated by using the GraphHeadFactory
   * @param ghf Generating the ids for the headers
   */
  public NestWithDisjunctive(GraphHeadFactory ghf) {
    super(ghf);
  }

  /**
   * A default id is associated to the graph
   * @param id Id to be associated to the new graph
   */
  public NestWithDisjunctive(GradoopId id) {
    super(id);
  }

}
