//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.08 at 11:00:43 AM CEST 
//


package org.gradoop.flink.io.impl.csv.pojos;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.gradoop.org/csvInput}label"/&gt;
 *         &lt;element ref="{http://www.gradoop.org/csvInput}key"/&gt;
 *         &lt;element ref="{http://www.gradoop.org/csvInput}source"/&gt;
 *         &lt;element ref="{http://www.gradoop.org/csvInput}target"/&gt;
 *         &lt;element ref="{http://www.gradoop.org/csvInput}graphs"/&gt;
 *         &lt;element ref="{http://www.gradoop.org/csvInput}properties"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "label",
    "key",
    "source",
    "target",
    "graphs",
    "properties"
})
@XmlRootElement(name = "edge")
public class Edge
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected Label label;
    @XmlElement(required = true)
    protected Key key;
    @XmlElement(required = true)
    protected Source source;
    @XmlElement(required = true)
    protected Target target;
    @XmlElement(required = true)
    protected Graphs graphs;
    @XmlElement(required = true)
    protected Properties properties;

    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link Label }
     *
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link Label }
     *
     */
    public void setLabel(Label value) {
        this.label = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return
     *     possible object is
     *     {@link Key }
     *
     */
    public Key getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value
     *     allowed object is
     *     {@link Key }
     *
     */
    public void setKey(Key value) {
        this.key = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return
     *     possible object is
     *     {@link Source }
     *
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value
     *     allowed object is
     *     {@link Source }
     *
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the target property.
     *
     * @return
     *     possible object is
     *     {@link Target }
     *
     */
    public Target getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     *
     * @param value
     *     allowed object is
     *     {@link Target }
     *
     */
    public void setTarget(Target value) {
        this.target = value;
    }

    /**
     * Gets the value of the graphs property.
     *
     * @return
     *     possible object is
     *     {@link Graphs }
     *
     */
    public Graphs getGraphs() {
        return graphs;
    }

    /**
     * Sets the value of the graphs property.
     *
     * @param value
     *     allowed object is
     *     {@link Graphs }
     *
     */
    public void setGraphs(Graphs value) {
        this.graphs = value;
    }

    /**
     * Gets the value of the properties property.
     *
     * @return
     *     possible object is
     *     {@link Properties }
     *
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

}
