//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.04 at 10:32:38 AM CET 
//


package org.gradoop.flink.io.impl.csv.pojos;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for objectreferences complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="objectreferences"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element ref="{http://www.gradoop.org/flink/io/impl/csv/pojos}static"/&gt;
 *           &lt;element ref="{http://www.gradoop.org/flink/io/impl/csv/pojos}ref"/&gt;
 *           &lt;element ref="{http://www.gradoop.org/flink/io/impl/csv/pojos}reference"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objectreferences", propOrder = {
    "staticOrRefOrReference"
})
@XmlSeeAlso({
    Graph.class
})
public class Objectreferences
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElements({
        @XmlElement(name = "static", type = Static.class),
        @XmlElement(name = "ref", type = Ref.class),
        @XmlElement(name = "reference", type = Reference.class)
    })
    protected List<Serializable> staticOrRefOrReference;

    /**
     * Gets the value of the staticOrRefOrReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the staticOrRefOrReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStaticOrRefOrReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Static }
     * {@link Ref }
     * {@link Reference }
     * 
     * 
     */
    public List<Serializable> getStaticOrRefOrReference() {
        if (staticOrRefOrReference == null) {
            staticOrRefOrReference = new ArrayList<Serializable>();
        }
        return this.staticOrRefOrReference;
    }

}
