//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.08 at 11:00:43 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gradoop.org/csvInput", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.gradoop.flink.io.impl.csv.pojos;
