/*
 * Copyright © 2014 - 2018 Leipzig University (Database Research Group)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradoop.flink.model.impl.operators.aggregation.functions.sum;

import org.gradoop.common.model.impl.pojo.Element;
import org.gradoop.common.model.impl.properties.PropertyValue;
import org.gradoop.common.model.impl.properties.PropertyValueUtils;
import org.gradoop.flink.model.impl.operators.aggregation.functions.BaseAggregateFunction;

/**
 * Superclass if aggregate functions that sum property values of elements.
 */
public abstract class SumProperty<T extends Element> extends BaseAggregateFunction<T> {

  /**
   * Prefix of the property key generated by {@link SumProperty} aggregate function.
   */
  private static final String PROPERTY_KEY_PREFIX_SUM = "sum_";

  /**
   * Constructor.
   *
   * @param propertyKey property key to aggregate
   */
  public SumProperty(String propertyKey) {
    super(propertyKey);
  }

  @Override
  public PropertyValue aggregate(PropertyValue aggregate, PropertyValue increment) {
    return PropertyValueUtils.Numeric.add(aggregate, increment);
  }

  @Override
  public PropertyValue getIncrement(T element) {
    return element.getPropertyValue(super.getAggregatePropertyKey());
  }

  @Override
  public String getAggregatePropertyKey() {
    return PROPERTY_KEY_PREFIX_SUM + super.getAggregatePropertyKey();
  }
}
